### ISSUE TITLE
The whole GUI blocks when training.

### ISSUE THREAD

**Issue by LinkinEminem** [Raspi-Project-16/fun_security_sys#14]
I just cloned the complete project into my Pi and tested it. It's really an amazing job. However, after I clicked the "train" button, the system started to training and the GUI was frozen for a while. When training is done, the GUI can work as usual.

I think it might be a good idea to use diferrent threads to run the training process and GUI.

**Comment by Lucas-ohmygoal** [comment]
That's a good idea. I will try to fix it. I'll let you know how it goes.

**Comment by Lucas-ohmygoal** [comment]
> 
I have submitted a new version, try it see if it works properly

**Comment by Lucas-ohmygoal** [comment]
This issue has been fixed
