### ISSUE TITLE
motor and light strip don't reset when switching from auto to manual mode

### ISSUE THREAD

**Issue by sugenyuan** [Raspi-Project-16/fun_security_sys#15]
While I'm testing it on my pi, I found the motor and light strip would stay at its previouse state and not reset to its initial position after I switch from automatic mode to manual mode. This might be a problem that we need to fix. Despit this, the project is great!

**Comment by Lucas-ohmygoal** [comment]
Yeah, it's a problem. I'll fix it as soon as possible.

**Comment by Lucas-ohmygoal** [comment]
I just saw you fixed the bug, excellent
